services:
  iris_backend_server_test:
    container_name: iris_ml_backend_test
    image: iris_ml_backend_server_test:latest
    build:
      context: ./backend
      args:
        INSTALL_DEV: true
    restart: always
    # volumes:
    #   - ./backend:/code
    ports:
      - 8000:8000
