services:
  iris_backend_server:
    container_name: iris_ml_backend
    image: iris_ml_backend_server:latest
    build:
      context: ./backend
    restart: always
    # volumes:
    #   - ./backend:/code
    ports:
      - 8000:8000
